### ISSUE TITLE
How to use the dynamic data as input

### ISSUE THREAD

**Issue by akcodehub** [sau026/ng-ticker-tape#1]
tickerData = [
        {
        'target_currency_short_name': ' BTT',
        'price': 0.00047020,
        'color': 'red',
        'percentage': 11.206+'%',
        'base_currency_short_name': '/USDT' 
        }];

tickerData = [
        {
        'ownlabel': ' BTT',
        'ownlabel': 0.00047020,
        'color': 'red',
        'ownlabel': 11.206+'%',
        'ownlabel': '/USDT' 
        },

**Comment by sau026** [comment]
This feature has not been implemented yet, I hope to add this feature in the coming days.

**Comment by sau026** [comment]
> tickerData = [
> {
> 'target_currency_short_name': ' BTT',
> 'price': 0.00047020,
> 'color': 'red',
> 'percentage': 11.206+'%',
> 'base_currency_short_name': '/USDT'
> }];
> 
> tickerData = [
> {
> 'ownlabel': ' BTT',
> 'ownlabel': 0.00047020,
> 'color': 'red',
> 'ownlabel': 11.206+'%',
> 'ownlabel': '/USDT'
> },

**Comment by sau026** [comment]
> tickerData = [
> {
> 'target_currency_short_name': ' BTT',
> 'price': 0.00047020,
> 'color': 'red',
> 'percentage': 11.206+'%',
> 'base_currency_short_name': '/USDT'
> }];
> 
> tickerData = [
> {
> 'ownlabel': ' BTT',
> 'ownlabel': 0.00047020,
> 'color': 'red',
> 'ownlabel': 11.206+'%',
> 'ownlabel': '/USDT'
> },

This feature has not been implemented yet, I hope to add this feature in the coming days.
